### ISSUE TITLE
Allow custom wordlists to be used

### ISSUE THREAD

**Issue by majjoha** [majjoha/passphrase#1]
Apart from the wordlist already in the repository, EFF also lists additional wordlists [here](https://www.eff.org/deeplinks/2018/08/dragon-con-diceware) and [here](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases). There is, currently, no functionality for handling custom wordlists, but it would be a useful feature to add.

For instance, in the following manner:
```
% stack exec -- passphrase short-wordlist.txt
```

By default, it should use the wordlist already shipped with the app, but if a path to a file is provided, it should read this file instead and, of course, fail gracefully in case the file does not exist or follow the expected format.

**Comment by sshine** [comment]
Hi :) Can I grab this? (My git repository spilled the beans.)

**Comment by majjoha** [comment]
Absolutely. Thanks! I'll let you know when I've had a chance to look at your pull request.
