### ISSUE TITLE
Sync Usage section in README.md with actual --help output

### ISSUE THREAD

**Issue by sshine** [majjoha/passphrase#6]
To prevent `--help` output and README.md from drifting apart, why not create a CI script that complains when the `## Usage` section does not match the output of running the executable? The script could be made such that it either complains or patches the README.md so that updating this section is semi-automatic. (One might consider a CI script that auto-commits to a PR when `--help` output changes, but I'm not sure I like automated checks causing commits for risk of automation cascades.)

**Comment by majjoha** [comment]
While I generally think it is good to ensure that the documentation and code stay in sync, I am also a bit hesitant to introduce and maintain the complexity for this. I'll close the issue for now and then revisit it later if it becomes a problem.
