### ISSUE TITLE
Answering "How do I install this thing?"

### ISSUE THREAD

**Issue by sshine** [majjoha/passphrase#7]
When `stack install` moves the `passphrase` binary to ~/.local/bin (or wherever), it would be neat if the program could access the default wordlist, or any alternate wordlists shipped with the program. Right now the default wordlist only works when sitting in the project directory. This task consists of investigating if `stack install` is sufficient for installing anything but the executable, such as word lists, or if program distribution should be handled in a way that places word lists somewhere like /usr/local/share.

**Comment by sshine** [comment]
I [asked on StackOverflow](https://stackoverflow.com/questions/66215545/hardcode-datadir-path-upon-installing-executable), and it seems that it isn't really that neat to use Stack as a tool for packaging the executable along with data files that would otherwise go into e.g. /usr/local/share. So either employ a build system like [Shake](https://shakebuild.com/) or [Bazel](https://bazel.build/), and/or [create an Ubuntu PPA](https://shallowsky.com/blog/programming/packaging-launchpad-ppas.html) in a way irrespective of Haskell's package build system.

**Comment by majjoha** [comment]
It is a good point. Thank you for mentioning it.

When time permits, I want to distribute it via [my personal Homebrew tap](https://github.com/majjoha/homebrew-tap), and this should also make it easier to place the wordlist in a sensible location. As a note to myself, a few Haskell projects that are distributed via Homebrew can be found in the list [here](https://github.com/Homebrew/homebrew-core/issues/55253).

I'll create a new issue for distributing the app via Homebrew instead.
