### ISSUE TITLE
Print ASCII art of rolled dice

### ISSUE THREAD

**Issue by sshine** [majjoha/passphrase#8]
It would be cool if there were an option to show illustrations of the dice rolled.

For inspiration, the [ASCII art archive on dice](https://www.asciiart.eu/miscellaneous/dice) contains some ideas, although my initial idea was something more readable, like:

```
.-------. .-------. .-------.
| o   o | | o     | | o   o |
|   o   | |   o   | | o   o | ...
| o   o | |     o | | o   o |
`-------' `-------' `-------'
```

Worth considering, Unicode has symbols for dice as well: ⚀⚁⚂⚃⚄⚅

The option could be `--draw` to enable drawings of dice next to the generated passphrase.

**Comment by majjoha** [comment]
The idea seems fun to me, and I might want to implement it in the future. For now, however, I want to keep the complexity of the project down, so I'll close the issue and perhaps reopen it if I end up changing my mind.
